
# 启用日志
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
#启用矩阵库
CONFIG_FPU=y
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_MATRIX=y
# 启用浮点支持
CONFIG_FPU_SHARING=y
CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n

# Optional: Enable RTT logging backend
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# 栈大小（FPU 需要更大的栈）
CONFIG_MAIN_STACK_SIZE=4096
